/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.wreulicke.sandbox;

import java.io.IOException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.junit.Test;

public class ServiceDiscoveryTest {
	
	private static final Logger log = LoggerFactory.getLogger(ServiceDiscoveryTest.class);
	
	@Test
	public void testSomeLibraryMethod() throws IOException {
	}
}
